/**
 * Specialty / Ethnic Store Data
 *
 * Contains store entries for specialty and ethnic grocery stores
 * serving specific cuisine communities in the UK.
 */

import { StoreInfo } from "./types";

/**
 * Specialty / ethnic store entries.
 * These serve specific cuisine communities and are matched during
 * onboarding cuisine selection.
 */
export const SPECIALTY_STORES: readonly StoreInfo[] = [
  {
    id: "wingyip",
    displayName: "Wing Yip",
    color: "#CC0000",
    type: "specialty",
    marketShare: 0.1,
    cuisines: ["chinese", "japanese", "korean", "thai", "vietnamese"],
    aliases: [
      "wing yip",
      "wing yip superstore",
      "wing yip oriental",
      "wing yip chinese",
      "wing yip birmingham",
      "wing yip manchester",
      "wing yip croydon",
      "wing yip cricklewood",
    ],
  },
  {
    id: "loonfung",
    displayName: "Loon Fung",
    color: "#D4262C",
    type: "specialty",
    marketShare: 0.1,
    cuisines: ["chinese", "japanese", "korean", "thai", "vietnamese"],
    aliases: [
      "loon fung",
      "loon fung supermarket",
      "loon fung chinese",
      "loon fung chinese supermarket",
    ],
  },
  {
    id: "seewoo",
    displayName: "SeeWoo",
    color: "#E31937",
    type: "specialty",
    marketShare: 0.1,
    cuisines: ["chinese", "japanese", "korean", "thai", "vietnamese"],
    aliases: [
      "seewoo",
      "see woo",
      "seewoo supermarket",
      "see woo chinese",
      "seewoo oriental",
      "see woo oriental",
    ],
  },
  {
    id: "hoo_hing",
    displayName: "Hoo Hing",
    color: "#B22222",
    type: "specialty",
    marketShare: 0.1,
    cuisines: ["chinese", "japanese", "korean", "thai", "vietnamese"],
    aliases: [
      "hoo hing",
      "hoohing",
      "hoo hing wholesale",
      "hoo hing chinese",
      "hoo hing oriental",
    ],
  },
  {
    id: "asian_supermarket",
    displayName: "Asian Store",
    color: "#FF6B35",
    type: "specialty",
    marketShare: 0.1,
    cuisines: ["chinese", "japanese", "korean", "thai", "vietnamese", "filipino"],
    aliases: [
      "asian supermarket",
      "oriental supermarket",
      "oriental grocery",
      "asian grocery",
      "chinese supermarket",
      "chinese grocery",
      "asian food store",
      "oriental store",
      "far east supermarket",
    ],
  },
  {
    id: "african_grocery",
    displayName: "African Store",
    color: "#009639",
    type: "specialty",
    marketShare: 0.1,
    cuisines: ["nigerian", "west-african", "east-african", "southern-african", "ethiopian", "caribbean"],
    aliases: [
      "african grocery",
      "african food store",
      "african store",
      "african supermarket",
      "afro caribbean store",
      "afro caribbean grocery",
      "african food market",
      "west african grocery",
      "east african grocery",
      "nigerian grocery",
      "nigerian store",
      "nigerian food store",
      "african market",
    ],
  },
  {
    id: "southasian_grocery",
    displayName: "Indian Store",
    color: "#FF9933",
    type: "specialty",
    marketShare: 0.1,
    cuisines: ["indian", "pakistani", "bangladeshi"],
    aliases: [
      "south asian grocery",
      "indian grocery",
      "indian store",
      "indian supermarket",
      "pakistani grocery",
      "pakistani store",
      "desi store",
      "desi grocery",
      "bangla grocery",
      "bangladeshi grocery",
      "sri lankan grocery",
      "asian grocery store",
    ],
  },
  {
    id: "middleeastern_grocery",
    displayName: "Middle Eastern Store",
    color: "#006847",
    type: "specialty",
    marketShare: 0.1,
    cuisines: ["middle-eastern", "turkish", "greek"],
    aliases: [
      "middle eastern grocery",
      "middle eastern store",
      "arabic grocery",
      "arab store",
      "halal grocery",
      "persian grocery",
      "turkish grocery",
      "turkish store",
      "lebanese grocery",
      "mediterranean grocery",
      "halal store",
      "halal supermarket",
    ],
  },
  {
    id: "latin_grocery",
    displayName: "Latin American Store",
    color: "#CE1126",
    type: "specialty",
    marketShare: 0.1,
    cuisines: ["mexican"],
    aliases: [
      "latin grocery",
      "latin american grocery",
      "latin american store",
      "mexican grocery",
      "mexican store",
      "latino store",
      "latin supermarket",
      "south american grocery",
    ],
  },
] as const;
