import { StyleSheet } from "react-native";
import { colors, typography, spacing, borderRadius } from "@/components/ui/glass";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.background.primary,
  },
  header: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xs,
  },
  headerTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: spacing.xs,
  },
  titleContainer: {
    flex: 1,
    marginRight: spacing.sm,
  },
  title: {
    ...typography.headlineMedium,
    color: colors.text.primary,
  },
  headerSecondRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: spacing.md,
  },
  subtitleContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    flex: 1,
  },
  subtitle: {
    ...typography.bodySmall,
    color: colors.text.secondary,
  },
  subtitlePlaceholder: {
    ...typography.bodySmall,
    color: colors.text.disabled,
    fontStyle: "italic",
  },
  secondRowActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.glass.background,
    justifyContent: "center",
    alignItems: "center",
    marginRight: spacing.md,
  },
  iconButtonSmall: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.glass.background,
    justifyContent: "center",
    alignItems: "center",
  },
  iconButtonActive: {
    backgroundColor: colors.glass.backgroundActive,
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.glass.background,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.md,
    height: 44,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.glass.border,
  },
  searchInput: {
    flex: 1,
    ...typography.bodyMedium,
    color: colors.text.primary,
    marginLeft: spacing.sm,
  },
  budgetCard: {
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  budgetRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  budgetInfo: {
    flex: 1,
  },
  budgetLabel: {
    ...typography.labelSmall,
    color: colors.text.tertiary,
    textTransform: "uppercase",
  },
  budgetValue: {
    ...typography.headlineSmall,
    color: colors.text.primary,
    marginTop: 2,
  },
  budgetStats: {
    flexDirection: "row",
    gap: spacing.md,
    marginTop: spacing.sm,
  },
  budgetStatItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  budgetStatText: {
    ...typography.bodySmall,
    color: colors.text.secondary,
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingHorizontal: spacing.lg,
    paddingBottom: 200,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.xs,
    marginTop: spacing.xs,
    marginBottom: spacing.xs,
  },
  sectionHeaderText: {
    ...typography.labelSmall,
    fontSize: 10,
    lineHeight: 14,
    color: colors.accent.primary,
    letterSpacing: 1.2,
    fontWeight: "700",
    marginRight: spacing.sm,
  },
  sectionHeaderLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.glass.border,
    opacity: 0.5,
  },
  toggleContainer: {
    paddingHorizontal: 0,
    marginBottom: spacing.md,
  },
  sectionTitle: {
    ...typography.labelMedium,
    color: colors.text.tertiary,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  sectionBadge: {
    backgroundColor: colors.glass.backgroundActive,
    borderRadius: borderRadius.full,
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
  },
  sectionBadgeText: {
    ...typography.labelSmall,
    color: colors.text.secondary,
    fontSize: 10,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 60,
    gap: spacing.md,
  },
  emptyIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.glass.background,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: spacing.sm,
  },
  emptyTitle: {
    ...typography.headlineSmall,
    color: colors.text.primary,
  },
  emptySubtitle: {
    ...typography.bodyMedium,
    color: colors.text.tertiary,
    textAlign: "center",
    maxWidth: 240,
    lineHeight: 22,
  },
  footer: {
    position: "absolute",
    left: 0,
    right: 0,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing["6xl"],
  },
  tripControls: {
    flexDirection: "row",
    gap: spacing.xs,
    alignItems: "center",
  },
  selectionBar: {
    position: "absolute",
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    backgroundColor: "rgba(13, 21, 40, 0.95)",
  },
  selectionInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  selectionCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.glass.background,
    justifyContent: "center",
    alignItems: "center",
  },
  selectionCount: {
    ...typography.labelMedium,
    color: colors.text.primary,
    fontWeight: "600",
  },
  selectionDeleteBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.semantic.danger,
    borderRadius: borderRadius.md,
  },
  selectionDeleteText: {
    ...typography.labelMedium,
    color: "#fff",
    fontWeight: "600",
  },
  checkedToggleBtn: {
    flex: 1,
    height: 48,
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: borderRadius.lg,
    backgroundColor: "#0F2A2A",
    borderWidth: 1,
    borderColor: colors.accent.primary,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 10,
  },
  checkedToggleBtnActive: {
    backgroundColor: "#0F2A2A",
    borderColor: colors.accent.primary,
  },
  checkedToggleText: {
    ...typography.labelMedium,
    color: colors.text.secondary,
    fontWeight: "600",
  },
  checkedToggleTextActive: {
    color: colors.accent.primary,
  },
  refreshPricesRow: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xs,
    paddingBottom: spacing.sm,
  },
  refreshPricesButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    alignSelf: "flex-start",
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: borderRadius.sm,
    backgroundColor: "rgba(0, 212, 170, 0.08)",
  },
  refreshPricesText: {
    ...typography.labelSmall,
    color: colors.accent.primary,
  },
  chatBadge: {
    position: "absolute" as const,
    top: -4,
    right: -6,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: colors.semantic.danger,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    paddingHorizontal: 3,
  },
  chatBadgeText: {
    fontSize: 9,
    fontWeight: "700" as const,
    color: "#fff",
  },
});
